---
title: "Team_Project_Part_II_Akshay"
author: "Akshay Punwatkar"
date: "10/29/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r Importing Libraries, message=FALSE, warning=FALSE}
library(lme4)
library(ggplot2)
library(ggcorrplot)
library(corrplot)
library(arm)
library(e1071)
library(caret)
library(pROC)
library(rms)
library(tidyverse)
library(ggpubr)
library(kableExtra)
library(knitr)
library(broom)
library(rlist)
```

## Reading Data

```{r Reading Data, message= FALSE}
#Reading file with data for all the voters
all_voter = read.csv("/Users/akshaypunwatkar/TeamProject2/team-project-2-estrogen-bioassay-and-voting-in-nc-avengers/Data/voter_stats_20161108.txt", 
                     header = TRUE, comment.char = "",sep='', stringsAsFactors = F)

#All voters -  514,846 Observations  (Actual number of rows in file)

#Getting unique rows from all_voters
all_voter = unique(all_voter)

#All voters -  461,833 Observations

#Reading file with data for the voters who actually voted 
voted_voter = read.delim("/Users/akshaypunwatkar/TeamProject2/team-project-2-estrogen-bioassay-and-voting-in-nc-avengers/Data/history_stats_20161108.txt")

#Voted voters - 734,126 Observations    (Actual number of rows in file)
#all unique rows in Voted_voters already

#renaming total_voter column in Voted_voters dataframe
colnames(voted_voter)[9] <- "voted_voters"

#Changing datatype of votes to numeric in both the dataframes
all_voter$total_voters = as.numeric(all_voter$total_voters)
voted_voter$voted_voters = as.numeric(as.character(voted_voter$voted_voters))
```

```{r Voter Turnout After Importing Data}
#Calculating total voting percentage 
Num_all_voters <- sum(all_voter$total_voters, na.rm = T)  #6,213,883  (Total voters)
Num_of_voted_voters <- sum(voted_voter$voted_voters)      #4,768,079  (Voters who voted)
Percent_Voted = (Num_of_voted_voters*100)/Num_all_voters  #76.73 % Voters Voted
```

```{r Data Cleaning}
#Removing unwanted columns (DATES & constant value stats_type columns)
all_voter$election_date <- NULL  
voted_voter$election_date <- NULL
voted_voter$update_date <- NULL
all_voter$stats_type <- NULL
voted_voter$stats_type <- NULL

#Removing Rows with empty data
#inital count of rows |  all_voter - 461,833, voted_voter - 734,126
all_v_noNA <- all_voter %>%
              na_if("") %>%
                na.omit()
#deleted 1026 rows with missing values (0.2%)

voted_v_noNA <- voted_voter %>%
                na_if("") %>%
                  na.omit()
#deleted 30,024 rows with missing values (4.0%)
#new count of rows  |   all_voter - 460,807, voted_voter  - 704,102

```

```{r Voter Turnout After Cleaning}

Num_all_voters <- sum(all_v_noNA$total_voters, na.rm = T)  #6,210,364  (Total voters)
Num_of_voted_voters <- sum(voted_v_noNA$voted_voters)      #4,572,359  (Voters who voted)
Percent_Voted = (Num_of_voted_voters*100)/Num_all_voters   #73.62 % Voters Voted

```

## Merging

```{r MERGING the two dataset, warning=FALSE}
votedDataMerged = voted_v_noNA %>% 
                    inner_join (all_v_noNA, 
                                by = c("county_desc" , "precinct_abbrv", "vtd_abbrv", 
                                        "party_cd", "race_code","ethnic_code","sex_code",       
                                         "age"))
#nrows in votedDataMerged 626,544

#removing noNA dataframes (not required anymore)
rm(voted_v_noNA,all_v_noNA)

#dropping voting_method column (same as voting_method_desc)
votedDataMerged$voting_method <- NULL

```

```{r Data Processing of merged dataset}

votedDataMerged$county_desc = as.factor(votedDataMerged$county_desc)
votedDataMerged$precinct_abbrv = as.factor(votedDataMerged$precinct_abbrv)
votedDataMerged$vtd_abbrv = as.factor(votedDataMerged$vtd_abbrv)
votedDataMerged$age = as.factor(votedDataMerged$age)
votedDataMerged$party_cd = as.factor(votedDataMerged$party_cd)
votedDataMerged$race_code = as.factor(votedDataMerged$race_code)
votedDataMerged$ethnic_code = as.factor(votedDataMerged$ethnic_code)
votedDataMerged$sex_code = as.factor(votedDataMerged$sex_code)

# changing factor levels
votedDataMerged$party_cd = relevel(votedDataMerged$party_cd, 'UNA')
votedDataMerged$sex_code = relevel(votedDataMerged$sex_code, 'U')
votedDataMerged$ethnic_code = relevel(votedDataMerged$ethnic_code, 'UN')
votedDataMerged$race_code = relevel(votedDataMerged$race_code, 'U')
# changing already factored variable to character and then again to factor (removing any extra factor)
votedDataMerged$voting_method_desc = as.character(votedDataMerged$voting_method_desc)
votedDataMerged$voting_method_desc = as.factor(votedDataMerged$voting_method_desc)
votedDataMerged$voted_party_cd = as.character(votedDataMerged$voted_party_cd)
votedDataMerged$voted_party_cd = as.factor(votedDataMerged$voted_party_cd)

# nrow(unique(votedDataMerged[,c("county_desc" , "precinct_abbrv", "vtd_abbrv",
#                            "party_cd", "race_code","ethnic_code","sex_code", 
#                            "age","voted_voters","voting_method_desc","voted_party_cd")]))

```

```{r Aggregating (Voted_Voters) in Merged Data}

voterStatDf <- aggregate(votedDataMerged$voted_voters, 
                          by=list(votedDataMerged$county_desc , votedDataMerged$precinct_abbrv, 
                                  votedDataMerged$vtd_abbrv,votedDataMerged$party_cd, 
                                  votedDataMerged$age,votedDataMerged$race_code,
                                  votedDataMerged$ethnic_code,votedDataMerged$sex_code,
                                  votedDataMerged$total_voters), sum) 

colnames(voterStatDf) <-  c("county_desc", "precinct_abbrv", "vtd_abbrv" ,"party_cd",   
                            "age", "race_code", "ethnic_code", "sex_code",  "total_voters",        
                            "voted_voters")
```

```{r Voter Turnout after Aggregating}
Num_all_voters <- sum(voterStatDf$total_voters)             #6,070,763 (Total voters)
Num_of_voted_voters <- sum(voterStatDf$voted_voters)        #4,097,895  (Voters who voted)
Percent_Voted = (Num_of_voted_voters*100)/Num_all_voters    #67.52% Voters Voted
```

```{r Checking Voted > Total}
## in voter data merged dataframe
nrow(votedDataMerged[votedDataMerged$voted_voters > votedDataMerged$total_voters,  ]) # 622 (0.1%)

## in Voter stats dataframe
nrow(voterStatDf[voterStatDf$voted_voters > voterStatDf$total_voters,  ]) # 3023 (0.84%)
```

```{r PLOTTING no of Observations for each County }
# dt = aggregate(voterStatDf$county_desc, list(voterStatDf$county_desc), length)
# colnames(dt) = c('County','NbrOfObs')
# 
# ggplot(dt)+
#   geom_bar(aes(x=County, y=NbrOfObs), stat = 'identity')+
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1, size = 3))
```

```{r PLOTTING Voter Turnout for each County}
dt = aggregate(voterStatDf$total_voters, list(voterStatDf$county_desc), sum)
colnames(dt) = c('County','NbrOfTotalVoters')
dt2 = aggregate(voterStatDf$voted_voters, list(voterStatDf$county_desc), sum)
colnames(dt2) = c('County','NbrOfVotedVoters')
dt3 = merge(dt, dt2, by = "County")
dt3 = mutate(dt3, percentVoted = round((NbrOfVotedVoters/NbrOfTotalVoters),2))

ggplot(dt3, aes(x=County))+
  geom_bar(aes(y=percentVoted*100,fill='County'), stat = 'identity', width = 0.4)+
  ggtitle("Voter Turnout for all Counties") +
  geom_text(data=dt3,aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
            vjust = 0.6, hjust= -0.2, angle=90, size=2.5) +
  ylim(0,100)+
  xlab("Counties")+
  ylab("Voter Turnout") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45,hjust = 1,size=2))
```

## Sampling

```{r Selecting 20 Counties at Random}
set.seed(98)
counties = sample(as.character(unique(votedDataMerged$county_desc)), size = 20,replace = T)

#Couting number of observations of 20 selected counties 

#print(counties)

# [1] "BERTIE"     "CALDWELL"   "FRANKLIN"   "DARE"      
# [5] "HARNETT"    "JONES"      "CHATHAM"    "SWAIN"     
# [9] "PAMLICO"    "BUNCOMBE"   "CHEROKEE"   "MCDOWELL"  
# [13] "STOKES"     "PITT"       "NASH"       "SURRY"     
# [17] "WARREN"     "TYRRELL"    "LENOIR"     "CUMBERLAND"

```

```{r Sampling data for 20 Counties}
#Subsetting data for 20 counties from merged and stats table
voting_dataset = subset(votedDataMerged, county_desc %in% counties)
voting_stats_dataset = subset(voterStatDf, county_desc %in% counties)

#Dropping merged dataset
#rm(voterStatDf)
#rm(votedDataMerged)
```

```{r Voter Turnout after Sampling}
Num_all_voters <- sum(voting_stats_dataset$total_voters)        #947,012 (Total voters)
Num_of_voted_voters <- sum(voting_stats_dataset$voted_voters)   #648,649  (Voters who voted)
Percent_Voted = (Num_of_voted_voters*100)/Num_all_voters        #68.49% Voters Voted
```

## EDA 

```{r PLOTTING no of Observations for 20 Counties}

dt = aggregate(voting_stats_dataset$county_desc, list(voting_stats_dataset$county_desc), length)
colnames(dt) = c('County','NbrOfObs')

ggplot(dt,aes(x=County, y=NbrOfObs),label=NbrOfObs)+
  geom_bar(stat='identity',fill='Blue2', width = 0.4)+
  ylim(0,15500)+
  geom_text(aes(label= scales::comma(NbrOfObs)),hjust=0.5,vjust=-0.8,size=3)+
  ggtitle("Number of Observations for 20 Counties") +
  theme( plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45,hjust = 1))
```

```{r Observations where Party has changed}
#Checking number observations where party has changed
nrow(voting_dataset[voting_dataset$party_cd != voting_dataset$voted_party_cd,]) #868 (0.8%)

# Since only 0.8% observations have different partycd and voted_party_cd. 
# Dropping voted_party_cd column

voting_dataset$voted_party_cd <- NULL
```

```{r PLOTTING County wise voter turnout}

dt = aggregate(c(voting_stats_dataset$total_voters), list(voting_stats_dataset$county_desc), sum)
colnames(dt) = c('County','NbrOfTotalVoters')
dt2 = aggregate(c(voting_stats_dataset$voted_voters), list(voting_stats_dataset$county_desc), sum)
colnames(dt2) = c('County','NbrOfVotedVoters')
dt3 = merge(dt, dt2, by = "County")
dt3 = mutate(dt3, percentVoted = round((NbrOfVotedVoters/NbrOfTotalVoters),2))

## Plotting number of total voters and count of voters who voted

# ggplot(dt3, aes(x=County))+
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.4)+
#   ggtitle("Distribution of Total Voter and Voted voters for 20 Counties") +
#   geom_text(data=dt3,aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             vjust = 0.6, hjust= -0.2, angle=90, size=2.5 ) +
#   ylim(0,200000)+
#   xlab("Counties")+
#   ylab("Voter Count") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))

ggplot(dt3, aes(x=County))+
  geom_bar(aes(y=percentVoted*100, fill=County), stat = 'identity', width = 0.4)+
  ggtitle("Voter Turnout for 20 Counties") +
  geom_text(data=dt3,aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
            vjust = -0.4, hjust= 0.4, angle=0, size=2.5 ) +
  ylim(0,100)+
  xlab("Counties")+
  ylab("Voter Turnout") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45,hjust = 1))
```

```{r PLOTTING Gender wise voter turnout}

dt = aggregate(c(voting_stats_dataset$total_voters), 
               list(voting_stats_dataset$sex_code), sum)
colnames(dt) = c('sex_code','NbrOfTotalVoters')
dt2 = aggregate(c(voting_stats_dataset$voted_voters), 
                list(voting_stats_dataset$sex_code), sum)
colnames(dt2) = c('sex_code','NbrOfVotedVoters')
dt3 = merge(dt, dt2, by = "sex_code")
dt3 = mutate(dt3, percentVoted = round((NbrOfVotedVoters/NbrOfTotalVoters),2))

## Plotting number of total voters and count of voters who voted

ggplot(dt3, aes(x=sex_code))+
  geom_bar(aes(y=percentVoted*100, fill=sex_code), stat = 'identity',  width = 0.3)+
  ggtitle("Gender-wise Voter Turnout") +
  geom_text(data=dt3,aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
            vjust = -0.4, hjust= 0.4, angle=0, size=4 ) +
  ylim(0,100)+
  xlab("Gender")+
  ylab("Voter Count") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45,hjust = 1))
```

```{r PLOTTING Gender and County wise voter turnout}
dt = aggregate(c(voting_stats_dataset$total_voters), 
               list(voting_stats_dataset$county_desc,voting_stats_dataset$sex_code), sum)
colnames(dt) = c('County',"Sex_code",'NbrOfTotalVoters')
dt2 = aggregate(c(voting_stats_dataset$voted_voters), 
                list(voting_stats_dataset$county_desc,voting_stats_dataset$sex_code), sum)
colnames(dt2) = c('County',"Sex_code", "NbrOfVotedVoters")
dt3 = merge(dt, dt2, by.x = c("County","Sex_code"), by.y=c("County","Sex_code"))
dt3 = mutate(dt3, percentVoted = round((NbrOfVotedVoters/NbrOfTotalVoters),2))

## plotting number of total voters and count of voters who voted 

## County Wise

# ggplot(dt3, aes(x=County))+
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2')+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2')+
#   ggtitle("County-wise Voter Turnout") +
#   geom_text(data=dt3,aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = -0.1, vjust = 0.5, angle=90, size=3) +
#   ylim(0,105000)+
#   xlab("Counties")+
#   ylab("Voter Count") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))+
#   facet_wrap(~Sex_code)
# 
# ## Gender Wise 
# 
# ggplot(dt3, aes(x=Sex_code))+
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.6)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.4)+
#   ggtitle("Gender-wise voter Turnout") +
#   geom_text(data=dt3,aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   ylim(0,105000)+
#   xlab("Counties")+
#   ylab("Voter Count") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))+
#   facet_wrap(~County)

ggplot(dt3, aes(x=County))+
  geom_bar(aes(y=percentVoted*100, fill=County), stat = 'identity')+
  ggtitle("County-wise Voter Turnout for Gender") +
  geom_text(data=dt3,aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
            hjust = -0.1, vjust = 0.5, angle=90, size=3) +
  ylim(0,110)+
  xlab("Counties")+
  ylab("Voter Turnout") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45,hjust = 1))+
  facet_wrap(~Sex_code)

### Based on the analysis, it seems for each county, the number of males and females who voted
### were comparable (+- 2%)
```

```{r PLOTTING Gender and Party wise voter turnout}
dt = aggregate(c(voting_stats_dataset$total_voters), 
               list(voting_stats_dataset$party_cd,voting_stats_dataset$sex_code), sum)
colnames(dt) = c('party_cd',"Sex_code",'NbrOfTotalVoters')
dt2 = aggregate(c(voting_stats_dataset$voted_voters), 
                list(voting_stats_dataset$party_cd,voting_stats_dataset$sex_code), sum)
colnames(dt2) = c('party_cd',"Sex_code", "NbrOfVotedVoters")
dt3 = merge(dt, dt2, by = c("party_cd","Sex_code"))
dt3 = mutate(dt3, percentVoted = round((NbrOfVotedVoters/NbrOfTotalVoters),2))

## Plotting

# female_party_plot <- ggplot(dt3[dt3$Sex_code=="F",], aes(x=party_cd))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Party-wise Voter-Turnout (Female)") +
#   geom_text(data=dt3[dt3$Sex_code=="F",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Party Code")+
#   ylab("Female Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# male_party_plot <- ggplot(dt3[dt3$Sex_code=="M",], aes(x=party_cd))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Party-wise Voter-Turnout (Male)") +
#   geom_text(data=dt3[dt3$Sex_code=="M",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Party Code")+
#   ylab("Male Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# U_party_plot <- ggplot(dt3[dt3$Sex_code=="U",], aes(x=party_cd))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Party-wise Voter-Turnout (U)") +
#   geom_text(data=dt3[dt3$Sex_code=="U",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Party Code")+
#   ylab("U Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# ggarrange(male_party_plot,female_party_plot,U_party_plot, ncol = 3)

ggplot(dt3, aes(x=party_cd))+ 
  geom_bar(aes(y=percentVoted*100,fill=party_cd), stat = 'identity', width = 0.4)+
  ggtitle("Party-wise Voter-Turnout for Gender") +
  geom_text(data=dt3,
            aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
            hjust = 0.5, vjust = -0.5, angle=0, size=3.5) +
  ylim(0,101)+
  xlab("Party Code")+
  ylab("Voter Turnout") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45,hjust = 1)) + facet_wrap(~Sex_code)

# ggplot(dt3, aes(x=Sex_code))+ 
#   geom_bar(aes(y=percentVoted*100,fill=Sex_code), stat = 'identity', width = 0.4)+
#   ggtitle("Gender-wise Voter-Turnout for Parties") +
#   geom_text(data=dt3,
#             aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   ylim(0,110)+
#   xlab("Gender Code")+
#   ylab("Voter Trunout") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1)) + facet_wrap(~party_cd)

```

```{r PLOTTING Gender and Age wise voter turnout}

dt = aggregate(c(voting_stats_dataset$total_voters), 
               list(voting_stats_dataset$age,voting_stats_dataset$sex_code), sum)
colnames(dt) = c('age',"Sex_code",'NbrOfTotalVoters')
dt2 = aggregate(c(voting_stats_dataset$voted_voters), 
                list(voting_stats_dataset$age,voting_stats_dataset$sex_code), sum)
colnames(dt2) = c('age',"Sex_code", "NbrOfVotedVoters")
dt3 = merge(dt, dt2, by = c("age","Sex_code"))
dt3 = mutate(dt3, percentVoted = round((NbrOfVotedVoters/NbrOfTotalVoters),2))


# female_age_plot <- ggplot(dt3[dt3$Sex_code=="F",], aes(x=age))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Age wise Voter-Turnout (Female)") +
#   geom_text(data=dt3[dt3$Sex_code=="F",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Age Groups")+
#   ylab("Female Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# male_age_plot <- ggplot(dt3[dt3$Sex_code=="M",], aes(x=age))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Age wise Voter-Turnout (Male)") +
#   geom_text(data=dt3[dt3$Sex_code=="M",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Age Groups")+
#   ylab("Male Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# u_age_plot <- ggplot(dt3[dt3$Sex_code=="U",], aes(x=age))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Age wise Voter-Turnout (U)") +
#   geom_text(data=dt3[dt3$Sex_code=="U",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Age Groups")+
#   ylab("U Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# ggarrange(female_age_plot,male_age_plot,u_age_plot, ncol = 3)

# ggplot(dt3, aes(x=Sex_code))+ 
#   geom_bar(aes(y=percentVoted*100), stat = 'identity',fill='blue3', width = 0.4)+
#   ggtitle("Age wise Voter-Turnout for Gender") +
#   geom_text(data=dt3,
#             aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
#             hjust = 0.4, vjust = -0.5, angle=0, size=4) +
#   ylim(0,100)+
#   xlab("Gender")+
#   ylab("Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))+facet_wrap(~age)

ggplot(dt3, aes(x=age))+ 
  geom_bar(aes(y=percentVoted*100,fill=age), stat = 'identity', width = 0.4)+
  ggtitle("Gender wise Voter-Turnout for Age Groups") +
  geom_text(data=dt3,
            aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
            hjust = 0.4, vjust = -0.5, angle=0, size=3.5) +
  ylim(0,100)+
  xlab("Age Groups")+
  ylab("Voter Turnout") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45,hjust = 1))+facet_wrap(~Sex_code)
```

```{r PLOTTING Gender and Race wise voter turnout}
dt = aggregate(c(voting_stats_dataset$total_voters), 
               list(voting_stats_dataset$race,voting_stats_dataset$sex_code), sum)
colnames(dt) = c('race',"Sex_code",'NbrOfTotalVoters')
dt2 = aggregate(c(voting_stats_dataset$voted_voters), 
                list(voting_stats_dataset$race,voting_stats_dataset$sex_code), sum)
colnames(dt2) = c('race',"Sex_code", "NbrOfVotedVoters")
dt3 = merge(dt, dt2, by = c("race","Sex_code"))
dt3 = mutate(dt3, percentVoted = round((NbrOfVotedVoters/NbrOfTotalVoters),2))

# 
# female_race_plot <- ggplot(dt3[dt3$Sex_code=="F",], aes(x=race))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Race wise Voter-Turnout (Female)") +
#   geom_text(data=dt3[dt3$Sex_code=="F",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Race")+
#   ylab("Female Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# male_race_plot <- ggplot(dt3[dt3$Sex_code=="M",], aes(x=race))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Race wise Voter-Turnout (Male)") +
#   geom_text(data=dt3[dt3$Sex_code=="M",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Race")+
#   ylab("Male Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# U_race_plot <- ggplot(dt3[dt3$Sex_code=="U",], aes(x=race))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Race wise Voter-Turnout (U)") +
#   geom_text(data=dt3[dt3$Sex_code=="U",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Race")+
#   ylab("U Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# 
# ggarrange(female_race_plot,male_race_plot,U_race_plot, ncol = 3)

ggplot(dt3, aes(x=race))+ 
  geom_bar(aes(y=percentVoted*100, fill=race), stat = 'identity', width = 0.4)+
  ggtitle("Race wise Voter-Turnout for Genders") +
  geom_text(data=dt3,
            aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
            hjust = 0.5, vjust = -0.5, angle=0, size=3) +
  xlab("Race")+
  ylab("Voter Turnout") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45,hjust = 1)) + facet_wrap(~Sex_code)

```

```{r PLOTTING Gender and Ethnicity wise voter turnout}
dt = aggregate(c(voting_stats_dataset$total_voters), 
               list(voting_stats_dataset$ethnic_code,voting_stats_dataset$sex_code), sum)
colnames(dt) = c('ethnic_code',"Sex_code",'NbrOfTotalVoters')
dt2 = aggregate(c(voting_stats_dataset$voted_voters), 
                list(voting_stats_dataset$ethnic_code,voting_stats_dataset$sex_code), sum)
colnames(dt2) = c('ethnic_code',"Sex_code", "NbrOfVotedVoters")
dt3 = merge(dt, dt2, by = c("ethnic_code","Sex_code"))
dt3 = mutate(dt3, percentVoted = round((NbrOfVotedVoters/NbrOfTotalVoters),2))

# female_ethnic_plot <- ggplot(dt3[dt3$Sex_code=="F",], aes(x=ethnic_code))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Ethnic-code wise Voter-Turnout (Female)") +
#   geom_text(data=dt3[dt3$Sex_code=="F",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Ethnic-code")+
#   ylab("Female Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# male_ethnic_plot <- ggplot(dt3[dt3$Sex_code=="M",], aes(x=ethnic_code))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Ethnic-code wise Voter-Turnout (Male)") +
#   geom_text(data=dt3[dt3$Sex_code=="M",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Ethnic-code")+
#   ylab("Male Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# U_ethnic_plot <- ggplot(dt3[dt3$Sex_code=="U",], aes(x=ethnic_code))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Ethnic-code wise Voter-Turnout (U)") +
#   geom_text(data=dt3[dt3$Sex_code=="U",],
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Ethnic-code")+
#   ylab("U Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5),
#         axis.text.x = element_text(angle = 45,hjust = 1))
# 
# ggarrange(female_ethnic_plot,male_ethnic_plot,U_ethnic_plot, ncol = 3)

ggplot(dt3, aes(x=ethnic_code))+ 
  geom_bar(aes(y=percentVoted*100, fill=ethnic_code), stat = 'identity', width = 0.4)+
  ggtitle("Ethnic-code wise Voter-Turnout for Gender") +
  geom_text(data=dt3,
            aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
            hjust = 0.5, vjust = -0.5, angle=0, size=3.5) +
  xlab("Ethnic-code")+
  ylab("Voter Turnout") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45,hjust = 1))+ facet_wrap(~Sex_code)

```

```{r PLOTTING Ethnicity and Age wise voter turnout}
dt = aggregate(c(voting_stats_dataset$total_voters), 
               list(voting_stats_dataset$ethnic_code,voting_stats_dataset$age), sum)
colnames(dt) = c('ethnic_code',"age",'NbrOfTotalVoters')
dt2 = aggregate(c(voting_stats_dataset$voted_voters), 
                list(voting_stats_dataset$ethnic_code,voting_stats_dataset$age), sum)
colnames(dt2) = c('ethnic_code',"age", "NbrOfVotedVoters")
dt3 = merge(dt, dt2, by = c("ethnic_code","age"))
dt3 = mutate(dt3, percentVoted = round((NbrOfVotedVoters/NbrOfTotalVoters),2))


# agewise_ethnic_plot <- ggplot(dt3, aes(x=age))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Age-wise Voter-Turnout for Ethnic groups") +
#   geom_text(data=dt3,
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Age")+
#   ylab("Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5, size=10),
#         axis.text.x = element_text(angle = 45,hjust = 1))+
#   facet_wrap(~ethnic_code)
# 
# ethnicwise_age_plot <- ggplot(dt3, aes(x=ethnic_code))+ 
#   geom_bar(aes(y=NbrOfTotalVoters), stat = 'identity', fill='Blue2', width = 0.4)+
#   geom_bar(aes(y=NbrOfVotedVoters), stat = 'identity', fill='Orange2', width = 0.2)+
#   ggtitle("Ethnicity-wise Voter-Turnout for Age groups") +
#   geom_text(data=dt3,
#             aes(y=NbrOfTotalVoters,label=scales::percent(percentVoted)), 
#             hjust = 0.5, vjust = -0.5, angle=0, size=3) +
#   xlab("Ehnic Code")+
#   ylab("Voters") +
#   theme(legend.position = "none",
#         plot.title = element_text(hjust = 0.5, size=10),
#         axis.text.x = element_text(angle = 45,hjust = 1))+
#   facet_wrap(~age)
# 
# ggarrange(agewise_ethnic_plot,ethnicwise_age_plot, ncol = 2)

ggplot(dt3, aes(x=age))+ 
  geom_bar(aes(y=percentVoted*100, fill=age), stat = 'identity', width = 0.4)+
  ggtitle("Age-wise Voter-Turnout for Ethnic groups") +
  geom_text(data=dt3,
            aes(y=percentVoted*100,label=scales::percent(percentVoted)), 
            hjust = 0.5, vjust = -0.5, angle=0, size=3) +
  xlab("Age Group")+
  ylab("Voter Turnout") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, size=10),
        axis.text.x = element_text(angle = 45,hjust = 1))+
  facet_wrap(~ethnic_code)

```

## Data Processing

```{r Removing Precints and Aggregating}

#length(unique(voting_stats_dataset$precinct_abbrv)) - 406
#length(unique(voting_stats_dataset$vtd_abbrv)) -361

#To many factors in precinct due to which Dropping precinct

Votes_Dataset = aggregate(list( voting_stats_dataset$total_voters,voting_stats_dataset$voted_voters),
                       by=list(voting_stats_dataset$county_desc , voting_stats_dataset$party_cd,
                               voting_stats_dataset$age,voting_stats_dataset$race_code,
                               voting_stats_dataset$ethnic_code,voting_stats_dataset$sex_code), sum) 

colnames(Votes_Dataset) <- c("county_desc","party_cd", "age", "race_code", "ethnic_code", 
                         "sex_code",  "total_voters", "voted_voters")
#rm(voting_dataset)
#rm(voting_stats_dataset)
#rm(all_voter)
#rm(voted_voter)
```

```{r Voter Turnout after aggregating }
Num_all_voters <- sum(Votes_Dataset$total_voters)        #947,012 (Total voters)
Num_of_voted_voters <- sum(Votes_Dataset$voted_voters)   #648,649 (Voters who voted)
Percent_Voted = (Num_of_voted_voters*100)/Num_all_voters #68.5 %
```

```{r Data Processing }

#dim(Votes_Dataset) # 7291 (rows) 
#Checking rows were voted voters are more than total voters 
#nrow(Votes_Dataset[Votes_Dataset$voted_voters > Votes_Dataset$total_voters,  ]) #39

# Updating total-vaters in rows with voted-voters > total-voters with the value of voted-voters
Votes_Dataset = mutate(Votes_Dataset, total_voters = ifelse(voted_voters>total_voters, voted_voters, total_voters))

#Checking rows were voted voters are more than total voters after updating
#nrow(Votes_Dataset[Votes_Dataset$voted_voters > Votes_Dataset$total_voters,  ]) # 0
```

```{r Voter Turnout after processing}
Num_all_voters <- sum(Votes_Dataset$total_voters)        #947,083 (Total voters)
Num_of_voted_voters <- sum(Votes_Dataset$voted_voters)   #648,649 (Voters who voted)
Percent_Voted = (Num_of_voted_voters*100)/Num_all_voters #68.48 %
```

```{r Chi-square test}
chi_age_party = chisq.test(Votes_Dataset$age,Votes_Dataset$party_cd) #significant / association exists
chi_sex_party = chisq.test(Votes_Dataset$sex_code,Votes_Dataset$party_cd) # boderline p / association exists
```

##Dataset - Votes_Dataset

## Modeling

```{r Model_1 Simple Logistic Regression}

Model_1 <- glm(cbind(voted_voters,total_voters-voted_voters) ~ county_desc + party_cd + 
               age + race_code + ethnic_code + sex_code, 
               data = Votes_Dataset, family = binomial)

summary(Model_1)
```

```{r Model_2 Hierarchical Modelling with Random Intercept as County}
Model_2 <- glmer(cbind(voted_voters,total_voters-voted_voters)  ~ (1|county_desc) +
                party_cd + age + race_code + ethnic_code + sex_code,
                 data = Votes_Dataset, family = binomial)

summary(Model_2)
```

```{r Model_3 Random Intercept as County and slope as Gender}
Model_3 <- glmer(cbind(voted_voters,total_voters-voted_voters) ~  (1|county_desc) + 
                party_cd + age + race_code + ethnic_code + sex_code +sex_code:party_cd,
                 data = Votes_Dataset, family = binomial)

summary(Model_3)
#dotplot(ranef(Model_3), conVar=T)
```

```{r ANOVA Model_2 and Model_3}
anova(Model_2, Model_3) #Model_3 is better
```


```{r Model_4}
Model_4 <- glmer(cbind(voted_voters,total_voters-voted_voters)  ~ (1|county_desc)+
                 (1|party_cd)+ age + race_code + ethnic_code + sex_code + sex_code:party_cd,
                 data = Votes_Dataset, family = binomial)

summary(Model_4)
#ranef(Model_4)
#dotplot(ranef(Model_4), conVar=T)
```


```{r Model_5}
Model_5 <- glmer(cbind(voted_voters,total_voters-voted_voters)  ~ (1|county_desc) + 
                 sex_code + party_cd + age + race_code + ethnic_code + sex_code:party_cd,
                 data = Votes_Dataset, family = binomial)

summary(Model_5)

ranef(Model_5)
```

```{r ANOVA Model_2 and Model_5}
anova(Model_2, Model_5) #Model_3 is better
```

```{r Model_6}
Model_6 <- glmer(cbind(voted_voters,total_voters-voted_voters)  ~ 
                 (1+county_desc|sex_code)+ age + race_code + ethnic_code  + sex_code:party_cd,
                 data = Votes_Dataset, family = binomial(link="logit"))

summary(Model_5)
```

```{r Decomposing  Votes_dataset }

decomp_votes <- rep(0,0)
for (i in seq(1,dim(Votes_Dataset[, c("total_voters", "voted_voters")])[1])) {
#for (i in seq(1,5)) {
 ones <- (rep(1, Votes_Dataset[i, c("total_voters", "voted_voters")]$voted_voters))
 zeros <- (rep(0, (Votes_Dataset[i, c("total_voters", "voted_voters")]$total_voters
                   - Votes_Dataset[i, c("total_voters", "voted_voters")]$voted_voters)))
 row_result <- list.append(ones,zeros)
 decomp_votes <- list.append(decomp_votes, row_result)
}

predicted = predict(Model_5, Votes_Dataset, type= "response")

pred_votes <- rep(0,0)
for (i in seq(1,length(predicted))) {
#for (i in seq(1,5)) {
  voted_people = round(Votes_Dataset[i,'total_voters']*predicted[i],0)
  ones <- (rep(1,voted_people))
  zeros <- (rep(0, (Votes_Dataset[i, 'total_voters']- voted_people)))
  pred_row_result <- list.append(ones,zeros)
  pred_votes <- list.append(pred_votes, pred_row_result)
}
str(decomp_votes)
str(pred_votes)

str()
confusionMatrix(factor(decomp_votes),factor(pred_votes))
```



### Analyzing Results

## Results



